04-26 21:25:39 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:684)
	at org.h2.server.web.WebApp.test(WebApp.java:896)
	at org.h2.server.web.WebApp.process(WebApp.java:222)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
04-26 21:25:39 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:684)
	at org.h2.server.web.WebApp.test(WebApp.java:896)
	at org.h2.server.web.WebApp.process(WebApp.java:222)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
04-26 21:28:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ([*]SERVER NVARCHAR(255), DATABASE NVARCHAR(255), ROOTNODE NVARCHAR(255), JARFILE NVARCHAR(255))"; expected "identifier"; SQL statement:
CREATE TABLE (SERVER NVARCHAR(255), DATABASE NVARCHAR(255), ROOTNODE NVARCHAR(255), JARFILE NVARCHAR(255)) [42001-176]
04-26 21:32:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SCHEMA" not found; SQL statement:
DROP TABLE SCHEMA [42102-176]
04-27 11:07:51 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.message.DbException.get(DbException.java:133)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1345)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1323)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:232)
	at uk.ac.uk.pwhelp01.uhuru.LocalDbDAO.updateSchema(LocalDbDAO.java:43)
	at uk.ac.uk.pwhelp01.uhuru.InnerProject.updateLocalDb(InnerProject.java:521)
	at uk.ac.uk.pwhelp01.uhuru.InnerProject.process(InnerProject.java:427)
	at uk.ac.uk.pwhelp01.uhuru.CreateSchemaController$1.call(CreateSchemaController.java:140)
	at uk.ac.uk.pwhelp01.uhuru.CreateSchemaController$1.call(CreateSchemaController.java:130)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
04-27 11:16:24 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.message.DbException.get(DbException.java:133)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1345)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1323)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:232)
	at uk.ac.uk.pwhelp01.uhuru.LocalDbDAO.updateSchema(LocalDbDAO.java:43)
	at uk.ac.uk.pwhelp01.uhuru.InnerProject.updateLocalDb(InnerProject.java:521)
	at uk.ac.uk.pwhelp01.uhuru.InnerProject.process(InnerProject.java:427)
	at uk.ac.uk.pwhelp01.uhuru.CreateSchemaController$1.call(CreateSchemaController.java:140)
	at uk.ac.uk.pwhelp01.uhuru.CreateSchemaController$1.call(CreateSchemaController.java:130)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
04-27 11:20:38 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "MERGE INTO SCHEMA (SERVER, DATABASE, ROOTNODE, JARFILE, TIMESTAMP) VALUES(:[*]SERVER, :DATABASE, :ROOTNODE, :JARLOCATION, CURRENT_TIMESTAMP); "; expected "), DEFAULT, NOT, EXISTS, SELECT, FROM"; SQL statement:
MERGE INTO SCHEMA (SERVER, DATABASE, ROOTNODE, JARFILE, TIMESTAMP) VALUES(:server, :database, :rootnode, :jarlocation, CURRENT_TIMESTAMP); [42001-140]
